Add CreditNotePreview
starkinfra/sdk-node pull request #13
Opened 2022-06-14 20:49 UTC by adryanalencar

2022-06-23 14:01 UTC, massaru-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * @param tax_amount [integer]: tax amount included in the CreditNote. ex: 100
Todos os parâmetros nas docstrings estão em snake_case, o padrão de javascript é camelCase

2022-06-23 14:01 UTC, massaru-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * @param rebate_amount [integer, default None]: credit analysis fee deducted from lent amount. ex: rebate_amount=11234 (= R$ 112.34)
"default null"

2022-06-23 14:07 UTC, massaru-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * @param initial_due [string]: date of the first invoice. ex: scheduled='2020-03-10'
O exemplo era pra ser initialDue, vi que deixamos passar errado no python, deixa isso mapeado naquele sheets pra gente arrumar na próxima alteração lá

2022-06-23 14:09 UTC, massaru-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +        this.interest = interest;
scheduled e initialDue precisam do check.datetimeOrDate()

2022-06-23 14:10 UTC, massaru-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * @param user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
default null

2022-06-23 14:13 UTC, massaru-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +        this.interest = interest;
Deixa as docstrings, parâmetros e corpo do construtor tudo na mesma ordem.

2022-06-23 14:16 UTC, massaru-stark commented on tests/testCreditNotePreview.js
> +        ;(await previews).forEach(preview => {
esse ; é parte da sintaxe mesmo?

2022-06-23 14:17 UTC, massaru-stark commented on tests/utils/creditNotePreview.js
> +const generatorsByType = {
Coloca essa constante pro começo do arquivo antes das funções

2022-06-23 14:18 UTC, massaru-stark commented on tests/utils/creditNotePreview.js
> +function getPreviewExamples(n=10, type){
Pode tirar esses enters desnecessários

2022-06-23 14:19 UTC, massaru-stark commented on tests/utils/creditNotePreview.js
> +}
Deixa esses exports padronizados com o resto do SDK

2022-06-23 14:24 UTC, massaru-stark commented on tests/utils/creditNotePreview.js
> +                  [...Array(n)].map(() => getPreviewExample())
Pode deixar esse ternário inline mesmo. Se for quebrar a linha, faz usando o if explícito

2022-06-23 15:16 UTC, adryanalencar commented on tests/testCreditNotePreview.js
> +        ;(await previews).forEach(preview => {
Sim

2022-07-06 14:24 UTC, joaogpw-stark requested changes

2022-07-06 14:24 UTC, joaogpw-stark commented on README.md
> +You can preview a Credit Note before creation of the CCB contract:
You can create a Credit Note Previews to preview a CCB contract
based on a specific table type:

2022-07-06 14:24 UTC, joaogpw-stark commented on README.md
> +    let previews = await starkinfra.creditNotePreview.create([
Eu comentaria ali pra destacar os diferentes tipos de tabela

2022-07-06 14:24 UTC, joaogpw-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * @param invoices [list of Invoice objects]: list of Invoice objects to be created and sent to the credit receiver. ex: invoices=[new Invoice(), new Invoice()]
Eu tiraria esse exemplo daqui, não descreve nd

2022-07-06 14:24 UTC, joaogpw-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * @param rebateAmount [integer, default null]: credit analysis fee deducted from lent amount. ex: rebate_amount=11234 (= R$ 112.34)
Aqui o default é 0

2022-07-06 14:24 UTC, joaogpw-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +                rebateAmount, amount, taxAmount, interest}) {
formatar melhor aqui

2022-07-06 14:24 UTC, joaogpw-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +     * Create CreditNotePreview
Create CreditNotePreview -> Create CreditNotePreviews

2022-07-06 14:24 UTC, joaogpw-stark commented on sdk/creditNotePreview/creditNotePreview.js
> +        this.invoices = parseOptionalObjects(invoices, invoiceResource, Invoice);
Não precisa de uma função específica para passear objetos opcionais. O parse objects não pode quebrar caso nada for passado. Pensa no CreditNote onde a invoice é required, se o usuário não passar a Invoice nós não queremos que o SDK quebre porque não existe nenhum mapeamento de erro, e sim que mande para a API a invoice vazia e a API retorne o erro.

2022-07-07 20:51 UTC, merged