Add request methods
starkinfra/sdk-node pull request #34
Opened 2024-06-11 17:43 UTC by leoKagohara-Stark

2024-06-25 01:07 UTC, luistarkbank commented on tests/testRequest.js
> +        let ext_id = Date.now().toString();
camelCase

2024-06-25 22:30 UTC, luistarkbank requested changes

2024-06-25 22:30 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"amount": 100}
não exatamente esse o body do post né kj

2024-06-25 22:30 UTC, luistarkbank commented on sdk/utils/rest.js
> +        prefix
ue ?? kjk

2024-06-27 19:49 UTC, leoKagohara-Stark commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"amount": 100}
não kkkk
Só um exemplo de json generico mesmo 😬

2024-06-28 01:39 UTC, luistarkbank requested changes

2024-06-28 01:39 UTC, luistarkbank commented on CHANGELOG.md
> +## [0.7.2] - 2024-05-09
o dotts não fez o bump ??

2024-06-28 01:39 UTC, luistarkbank commented on README.md
> +    let cursor = None
null

2024-06-28 01:39 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"amount": 100}
eu acho que vale a pena ter o exemplo de um possivel json no post, isso pode confundir o cliente

2024-06-28 01:39 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"amount": 100}
voce não passa body no delete

2024-06-28 01:39 UTC, luistarkbank commented on tests/testRequest.js
> +        this.exampleId = request["content"]["holders"][0]["id"];
esse "this.exampleId" ta certo ?? qual é a classe refereciada ??

2024-06-28 21:57 UTC, leoKagohara-Stark commented on CHANGELOG.md
> +## [0.7.2] - 2024-05-09
ainda nã

2024-07-01 14:40 UTC, luistarkbank requested changes

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param query [object, default None]: Query parameters. ex: {"limit": 1, "status": paid}
null, da um check geral

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"amount": 100}
dict ??

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"amount": 100}
e esse exemplo não funciona kj

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param path [string]: StarkBank resource's route. ex: "/pix-request/"
ta escrito starkbank, deveria ser algo tipo "Stark resouce's route...", sa um check geral

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @description Receive a json of resources previously created in StarkBank's API
aqui tbm

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
dict

2024-07-01 14:40 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
o exemplo anterior estava certo, pois hoje a gente fazer patchId, para a atualizar um objeto, mas voce pode usar esse exemplo no de cima

2024-07-02 21:08 UTC, danielterra-stark approved these changes

2024-07-03 12:11 UTC, merged