Fix/resources
starkinfra/sdk-node pull request #7
Opened 2022-05-18 17:34 UTC by massaru-stark

2022-05-18 19:53 UTC, joaogpw-stark requested changes

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixChargeback/log/log.js
> +     * PixChargebacks Log object
Todas as substituições ficaram no plural, tem que checar tudo aqui pra arrumar

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixDomain/pixDomain.js
> +     * @description The PixDomain object displays the QR Code domain certificate information of Pix participants.
Sugestão:
`The PixDomain object displays the domain name and the QR Code domain certificate of Pix participants.`

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixDomain/pixDomain.js
> +     * @param certificates [list of PixDomain.Certificate]: certificate information of the Pix participant.
Faltou adicionar o objeto Certificate e colocar o parse pra tirar os objetos

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixInfraction/index.js
> +exports.delete = pixInfraction.cancel;
.

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixInfraction/pixInfraction.js
> +     * @description Create a PixInfraction in the Stark Infra API
Plural:
`Create PixInfractions ...`

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixInfraction/pixInfraction.js
> +     * @returns PixInfraction object with updated attributes.
Plural:
`List of PixInfraction ...`

2022-05-18 19:53 UTC, joaogpw-stark commented on sdk/pixKey/index.js
> +exports.delete = pixKey.cancel;
.

2022-05-18 19:53 UTC, joaogpw-stark commented on tests/testCreditNote.js
> +    payment: {
O objeto transferir foi testado?

2022-05-18 19:53 UTC, joaogpw-stark commented on tests/testCreditNote.js
>      signers: [
Testou o signers

2022-05-18 22:22 UTC, massaru-stark commented on tests/testCreditNote.js
>      signers: [
Sim!

2022-05-20 17:07 UTC, joaogpw-stark requested changes

2022-05-20 17:07 UTC, joaogpw-stark commented on sdk/webhook/webhook.js
> +         * Currently available services for subscription are contract, credit-note, signer, issuing-card, issuing-invoice, issuing-purchase, pix-request.in, pix-request.out, pix-reversal.in, pix-reve
Adicionar as novas

2022-05-20 17:07 UTC, joaogpw-stark commented on tests/testPixChargeback.js
> +            let deletedPixChargeback = await starkinfra.pixChargeback.cancel(chargeback.id);
Eu daria um search all pra trocar esses deleted pra canceled

2022-05-20 17:07 UTC, joaogpw-stark commented on tests/utils/webhook.js
> +};
1) Precisa resolver os comentários finais do sheets la. Não esquece de adicionar as novas subscriptions no evento e no readme.
2) Eu percebi que não tem linha vazia no fim de todos os arquivos de node, é normal isso?

2022-05-20 18:24 UTC, joaogpw-stark approved these changes

2022-05-20 22:01 UTC, merged